feat: support parsing `html` via `@html-eslint/parser` natively
prettier/eslint-plugin-prettier pull request #652
Opened 2024-04-02 06:43 UTC by Logicer16

See https://github.com/prettier/eslint-plugin-prettier/pull/621#issuecomment-1866692220

Closes #651 

Currently blocked by https://github.com/yeonjuan/html-eslint/issues/184 for the parser's meta object.

Please let me know if there's anything else I should include.

2024-04-03 01:23 UTC, JounQin requested changes

2024-04-03 01:23 UTC, JounQin commented on worker.js
> +              !/([\\/])@html-eslint\/parser\1/.test(parserPath))
```suggestion
              !/([\\/])@html-eslint\1parser\1/.test(parserPath))
```

2024-04-03 07:23 UTC, Logicer16 commented on worker.js
> +              !/([\\/])@html-eslint\/parser\1/.test(parserPath))
Good find!

2024-04-07 06:13 UTC, JounQin approved these changes

2024-04-09 04:53 UTC, JounQin commented on .changeset/rich-swans-itch.md
> +"eslint-plugin-prettier": patch
```suggestion
"eslint-plugin-prettier": minor
```

2024-04-09 05:03 UTC, JounQin commented
test

2024-04-09 05:05 UTC, merged